apiVersion: v1
entries:
  certs:
  - apiVersion: v1
    created: 2019-09-29T13:17:27.059444+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 3da84ee0e0784e36c73fd263156c1f56b446c3ed6ad59ede55192de7f8d21a1e
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v1
    created: 2019-09-29T13:17:27.058881+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 135c957157f4ac2e63ec080281d6ba62a0b55cb23b6d36970faa67ccf1d1cb92
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    created: 2019-09-29T13:17:27.05773+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: f5cf55b0d3b4660e2a6389d901bb363ef95fc93cd078467b7d5d94dde3a9c954
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    created: 2019-09-29T13:17:27.053643+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 6820dce64a8580480994c48db545810a3db2f4ee63d750a346dc2db1dab5492d
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    created: 2019-09-29T13:17:27.05232+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: df1b855bbb58fb796087e4e032a0ba1b347320630e7c8e52c26a11c4be02e1ba
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    created: 2019-09-29T13:17:27.051344+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 3003a9dec1733d144168b2d6c0090ed6bd449f21cca31cd39997f20288d2ab1f
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-09-29T13:17:27.050127+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 790b6902ad4b95bcfd6f6906d2f028d7fd723e8fecb4c5774b9b6c565b104aae
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.0.0.tgz
    version: 1.0.0
generated: 2019-09-29T13:17:27.048816+02:00
